# OPD-prefixed secrets (to be filled by bw_secrets_to_vault.sh)
OPD_POSTGRES_USER: <Bitwarden:OPD_POSTGRES_USER>
OPD_POSTGRES_PASSWORD: <Bitwarden:OPD_POSTGRES_PASSWORD>
OPD_POSTGRES_DB: <Bitwarden:OPD_POSTGRES_DB>
OPD_TIMESCALE_USER: <Bitwarden:OPD_TIMESCALE_USER>
OPD_TIMESCALE_PASSWORD: <Bitwarden:OPD_TIMESCALE_PASSWORD>
OPD_TIMESCALE_DB: <Bitwarden:OPD_TIMESCALE_DB>
OPD_RABBITMQ_USER: <Bitwarden:OPD_RABBITMQ_USER>
OPD_RABBITMQ_PASSWORD: <Bitwarden:OPD_RABBITMQ_PASSWORD>
OPD_HCLOUD_TOKEN: <Bitwarden:OPD_HCLOUD_TOKEN>
COOLIFY_SECRET_KEY: <Bitwarden:COOLIFY_SECRET_KEY>
