# Add labels to PR based on the paths that are modified in the PR
ingestion:
  - changed-files:
    - any-glob-to-any-file: 'opendiscourse/ingestion/**'

documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
    - any-glob-to-any-file: 'docs/**'

tests:
  - changed-files:
    - any-glob-to-any-file: 'tests/**'

database:
  - changed-files:
    - any-glob-to-any-file: '**/*.sql'
    - any-glob-to-any-file: 'src/database/**'

scripts:
  - changed-files:
    - any-glob-to-any-file: 'scripts/**'

dependencies:
  - changed-files:
    - any-glob-to-any-file: 'requirements/**'
    - any-glob-to-any-file: 'pyproject.toml'
    - any-glob-to-any-file: 'setup.py'
    - any-glob-to-any-file: 'package.json'
    - any-glob-to-any-file: 'pnpm-lock.yaml'

github-actions:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

frontend:
  - changed-files:
    - any-glob-to-any-file: 'web/**'
    - any-glob-to-any-file: 'webui/**'
